export enum Command {
    
    TEST = "TEST",
    DBG = "DBG",
    DATA = "DATA",
    HALT = "HALT",
    RESET = "RESET",
    TITLE = "TITLE",
    SCREEN = "SCREEN",
    GOTO = "GOTO",
    CALL = "CALL",
    RET = "RET",
    VAR = "VAR",
    ARR_NEW = "ARR.NEW",
    ARR_SET = "ARR.SET",
    ARR_PUSH = "ARR.PUSH",
    INC = "INC",
    DEC = "DEC",
    PAL = "PAL",
    CHR = "CHR",
    WCOL = "WCOL",
    CLS = "CLS",
    VSYNC = "VSYNC",
    OUT = "OUT"
}
